### PR TITLE
Some chores to maintain the builder repo

### PR DESCRIPTION
**Pull request by Cryptophobia**
Just adding a Travis CI badge and updating the google api package of the builder here.

### CODE REVIEW

**Comment by Cryptophobia** [comment]
Waiting for https://travis-ci.org/teamhephy/builder/builds/633485239 to pass. Please approve after it passes.

**Comment by Cryptophobia** [comment]
@kingdonb @felixbuenemann @jfuechsl 

Looks like we are having some problems with the CI. The new linting framework and defaults seems to be conflicting with the way Travis CI runs. I am getting these errors on my local and when Travis CI runs: 

```
make test
docker run --rm -v ~/.gvm/pkgsets/go1.12/global/src/github.com/teamhephy/builder:/go/src/github.com/teamhephy/builder -w /go/src/github.com/teamhephy/builder quay.io/deis/go-dev:v1.25.0 lint
Manadatory Linters: These must pass
WARNING: deadline exceeded by linter gosimple (try increasing --deadline)
WARNING: deadline exceeded by linter vet (try increasing --deadline)
Optional Linters: These should pass
make: *** [Makefile:40: test-style] Error 2
```

@felixbuenemann and I talked about this before and I tried upgrading to the latest v1.25.0 deis/docker-go-dev image from the https://github.com/deis/docker-go-dev repo but looks like we are hitting deadlines on the golang linters.

We may need to change some settings on `.travis.yaml` file or set something like this inside of the docker-go-dev image:

https://github.com/containerd/cri/pull/18/files#diff-83d3bece9ef3c3ec577fe99d5a3078bdL32-R32

Can you guys take a look whenever you get a chance? If we can get this to work we can upgrade all other golang projects to use the newest docker go-dev image as well and upgrade our downstream clone repo https://github.com/teamhephy/docker-go-dev and make a base golang dev images from there.

**Comment by kingdonb** [comment]
I am taking a look at this, to see if I can reproduce those results and I will post an update when I'm able to confirm and can see what needs to change.

**Comment by kingdonb** [comment]
I am suspicious from the exact output that you posted (I got the same results) that the error is something other than the deadline exceeded, they are marked as warnings, and it seems to get into the next section for Optional Linters before failing.

Nonetheless the change may be needed in the go-dev image, and I did find where a 20s deadline was set, I have adjusted it upward and am building an image at `quay.io/kingdonb/go-dev:v1.25.1-kpb` that we can use to validate and answer that question. If that does not work, the next step I think is to try and run those linters by hand, perhaps there is an extra verbose mode, or maybe something else going wrong that can be made clearer with `set -x` or similar change.

**Comment by Cryptophobia** [comment]
Good work, not sure what is going on either. What I do know is that the line `Optional Linters: These should pass` always outputs even when the deadline breaks the execution. I'm pretty sure that is nonblocking code in Golang that outputs that line.

**Pull request merged**
