### PR TITLE
fix(glide): fix build dependencies using glide

### PR DESCRIPTION
**Pull request by Cryptophobia**
Fixing the build as we are having problems with glide pulling from mercurial vcs.

### CODE REVIEW

**Comment by till** [comment]
@Cryptophobia maybe `go dep` instead? I think glide's already "dead" again?
https://blog.algogrit.com/posts/2018-02-17-migrating-from-glide-to-dep/

**Comment by Cryptophobia** [comment]
@till , thank you for the idea. I'm going to try it now that it builds successfully locally. We should eventually just migrate to go modules and start using go version 1.12+ but we need to workout some of the dependencies first.

**Comment by till** [comment]
Makes sense, I had forgotten about go modules. Now that you mention it, I think I migrated internal software from glide, to go dep, to modules within a couple of days. 😂

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Cryptophobia** [comment]
@kingdonb @rwos @till  Lots of things broke since we updated https://github.com/teamhephy/distribution with upstream https://github.com/docker/distribution . I will need to re-examine this. Two things I would like to do next:

1) Rewrite the usage of interface context.Context in builder for docker context
2) Start using godep and hopefully ditch glide :joy:

**Review by kingdonb — APPROVED** [review]
:+1: LGTM

**Pull request merged**
